config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'user/index'
  get 'user/show'
  get 'user/new'
  get 'user/create'
  get 'user/destroy'
  resources :main_banners
  root 'main#home'

  get 'home', to: 'main#home', as: :home
  get 'privacy_policy', to: 'main#privacy_policy', as: :privacy_policy
  get 'terms_and_conditions', to: 'main#terms_and_conditions', as: :terms_and_conditions
  get 'frequent_questions', to: 'main#frequent_questions', as: :frequent_questions
  get 'who_we_are', to: 'main#who_we_are', as: :who_we_are
  get 'contact_us', to: 'main#contact_us', as: :contact_us
  get '/product/model_ea2', to: 'main#model_ea2', as: :model_ea2

  # log in page with form:
  get '/login'     => 'sessions#new', as: :login_form
  post '/login'    => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  get 'admin/dashboard', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main_banner.rb
class MainBanner < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize

  def dashboard
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :admin_page?
  helper_method :authorize
  helper_method :username

  protected

  def admin_page?
    (request.original_fullpath.include? 'admin') || (request.original_fullpath.include? 'login')
  end

  def authorize
    if session[:user_id].nil?
      flash[:warning] = 'Por favor, primero identifíquese.'
      redirect_to login_form_path and return
    end
  end

  def username
    session[:username]
  end
end

app/controllers/main_banners_controller.rb
class MainBannersController < ApplicationController
  before_action :authorize
  before_action :set_main_banner, only: [:show, :edit, :update, :destroy]

  # GET /main_banners
  # GET /main_banners.json
  def index
    @main_banners = MainBanner.all
  end

  # GET /main_banners/1
  # GET /main_banners/1.json
  def show
  end

  # GET /main_banners/new
  def new
    @main_banner = MainBanner.new
  end

  # GET /main_banners/1/edit
  def edit
  end

  # POST /main_banners
  # POST /main_banners.json
  def create
    @main_banner = MainBanner.new(main_banner_params)

    respond_to do |format|
      if @main_banner.save
        format.html { redirect_to @main_banner, notice: 'Main banner was successfully created.' }
        format.json { render :show, status: :created, location: @main_banner }
      else
        format.html { render :new }
        format.json { render json: @main_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_banners/1
  # PATCH/PUT /main_banners/1.json
  def update
    respond_to do |format|
      if @main_banner.update(main_banner_params)
        format.html { redirect_to @main_banner, notice: 'Main banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @main_banner }
      else
        format.html { render :edit }
        format.json { render json: @main_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_banners/1
  # DELETE /main_banners/1.json
  def destroy
    @main_banner.destroy
    respond_to do |format|
      format.html { redirect_to main_banners_url, notice: 'Main banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_banner
      @main_banner = MainBanner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_banner_params
      params.require(:main_banner).permit(:title, :order, :photo)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def privacy_policy
    #@legal_content = '# Hello Markdown'
  end

  def terms_and_conditions
  end

  def frequent_questions
  end

  def who_we_are
  end

  def contact_us
  end

  def model_ea2
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:username].downcase)

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      session[:username] = user.name

      flash[:notice] = 'Bienvenido ' + user.name
      redirect_to dashboard_path
    else
      flash[:error] = 'Usuario o contraseña incorrecto, por favor intente de nuevo'
      redirect_to login_form_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil

    flash[:notice] = 'Hasta pronto!'
    redirect_to login_form_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authorize

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_banners_helper.rb
module MainBannersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/dashboard.html.erb
<div class="background-container">
  <div id="admin-container" class="d-flex">

    <div class="admin-menu mr-3">

      <div class="d-flex flex-row user-menu align-items-center pl-5">
        <div class="d-flex flex-column mt-4">
          <img src="/img/woman-user.png" class="mx-auto mb-1" alt="Imagen de Usuario">
          <h4 class="mx-auto">Bienvenida <%= username %></h4>
        </div>
        <div class="ml-5">
          <a href="/logout" class="d-flex flex-row align-items-center">
            <p class="mb-0 mr-1">Salir</p>
            <i class="fas fa-sign-out-alt"></i>
          </a>
        </div>

      </div>

      <div class="d-flex flex-column content-menu mt-1 pb-4">
        <a href="#" class="admin-menu-link pl-5">Banners</a>

        <a href="#" class="admin-menu-link pl-5">Promociones</a>

        <a href="#" class="admin-menu-link pl-5">Productos</a>

        <a href="#" class="admin-menu-link pl-5">Artículos (Blog)</a>

        <a href="#" class="admin-menu-link pl-5">Imágenes de Artículos</a>

        <a href="#" class="admin-menu-link pl-5">Servicios</a>

        <a href="#" class="admin-menu-link pl-5">Encuentra tu distribuidor</a>

        <a href="#" class="admin-menu-link pl-5">Términos y condiciones</a>

        <a href="#" class="admin-menu-link pl-5">Aviso de Privacidad</a>

        <a href="#" class="admin-menu-link pl-5">Compañía</a>

        <a href="#" class="admin-menu-link pl-5">Misión</a>

        <a href="#" class="admin-menu-link pl-5">Visión</a>
      </div>
    </div>

    <div class="flex-grow-1 admin-body">
      <div class="d-flex">
        <h1>Banners Principales</h1>
      </div>

      <div class="mt-4">
        <h2>Agregar Banner</h2>
        <hr class="w-75 ml-0 mt-0" />
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">

    <title>EcoaradoWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">

    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<!--    <script>-->
<!--        window.marked = marked;-->
<!--    </script>-->

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if admin_page? %>
      <%#= render 'shared/admin_top_menu' %>
    <% else %>
      <%= render 'shared/top_menu' %>
    <% end %>

    <% if admin_page? %>
      <%= render 'shared/flashes' %>
    <% end %>

    <%= yield %>

    <% if admin_page? %>
      <%#= render 'shared/admin_footer' %>
    <% else %>
      <%= render 'shared/footer' %>
    <% end %>

    <script>
      let contentDiv = $('#legal-content')[0];
      if (typeof contentDiv === "undefined")
        contentDiv = $('#post-content')[0];

      if (typeof contentDiv !== "undefined")
        contentDiv.innerHTML = marked(contentDiv.innerHTML);
    </script>
  </body>
</html>

app/views/main/_banners.erb
<div id="banners-container-mobile" class="d-block d-md-none">
  <div id="carouselBannerMobile" class="banners-div carousel slide" data-ride="carousel">
    <ol class="carousel-indicators d-flex mb-1">
      <li data-target="#carouselBannerMobile" data-slide-to="0" class="active mr-2"></li>
      <li data-target="#carouselBannerMobile" data-slide-to="1" class="mr-2"></li>
      <li data-target="#carouselBannerMobile" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="d-flex justify-content-center align-items-center">
          <p class="text-banner-mobile mx-5">El regreso de la vida a la tierra</p>
          <img class="d-block w-100" src="/img/banner-mobile-1.jpg" alt="El regreso de la vida a la tierra">
        </div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center align-items-center">
          <p class="text-banner-mobile mx-5">Tecnología única en el mundo a disposición de los agricultores</p>
          <img class="d-block w-100" src="/img/banner-mobile-2.jpg" alt="Tecnología única en el mundo a disposición de
                                                                  los agricultores">
        </div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center align-items-center">
          <p class="text-banner-mobile mx-5">
            Nuestros equipos ahorran hasta el 50% de los combustibles y los costos de
            producción
          </p>
          <img class="d-block w-100" src="/img/banner-mobile-3.jpg" alt="Nuestros equipos ahorran hasta el 50% de los
                                                                      combustibles y los costos de producción">
        </div>
      </div>
    </div>

    <a class="carousel-control-prev" href="#carouselBannerMobile" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselBannerMobile" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div id="banners-container" class="d-none d-md-block">
  <div id="carouselBannerDesktop" class="banners-div carousel slide" data-ride="carousel">
    <ol class="carousel-indicators d-flex">
      <li data-target="#carouselBannerDesktop" data-slide-to="0" class="active mr-2"></li>
      <li data-target="#carouselBannerDesktop" data-slide-to="1" class="mr-2"></li>
      <li data-target="#carouselBannerDesktop" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="d-flex justify-content-center align-items-center">
          <p class="d-flex mx-5 px-5 text-banner">El regreso de la vida a la tierra</p>
          <img class="d-block w-100" src="/img/banner-1.jpg" alt="El regreso de la vida a la tierra">
        </div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center align-items-center">
          <p class="d-flex mx-5 px-5 text-banner">Tecnología única en el mundo a disposición de los agricultores</p>
          <img class="d-block w-100" src="/img/banner-2.jpg" alt="Tecnología única en el mundo a disposición de
                                                                  los agricultores">
        </div>
      </div>
      <div class="carousel-item">
        <div class="d-flex justify-content-center align-items-center">
          <p class="d-flex mx-5 px-5 text-banner">
            Nuestros equipos ahorran hasta el 50% de los combustibles y los costos de
            producción
          </p>
          <p></p>
          <img class="d-block w-100" src="/img/banner-3.jpg" alt="Nuestros equipos ahorran hasta el 50% de los
                                                                combustibles y los costos de producción">
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselBannerDesktop" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselBannerDesktop" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/main/_contact.erb
<div id="contact-div" class="contact-container mt-4 mt-md-5 pt-md-5 mx-3 mx-md-0">
  <div class="contact-information w-100 w-md-50 mx-auto d-flex justify-content-center">
    <div>
      <div id="contact-desktop" class="d-none d-md-flex flex-column my-3">
        <p class="header d-flex justify-content-center mb-0">Contacto</p>
        <p class="description d-flex justify-content-center">Fetasa-ECOARADO: Emiliano Zapata,</p>
        <p class="description d-flex justify-content-center">80260 Culiacán Rosales,</p>
        <p class="description d-flex justify-content-center">Sinaloa. México.</p>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Email:</p>
          <p class="description">info@eco-arado.com</p>
        </div>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Teléfono:</p>
          <p class="description">+52 667 531 4339</p>
        </div>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Celular:</p>
          <p class="description">+52 311 262 3949</p>
        </div>
      </div>

      <div id="contact-mobile" class="d-flex flex-column d-md-none py-2">
        <p class="header d-flex justify-content-center mb-0">Contacto</p>
        <p class="description d-flex justify-content-center">Fetasa-ECOARADO: Emiliano</p>
        <p class="description d-flex justify-content-center">Zapata,</p>
        <p class="description d-flex justify-content-center">80260 Culiacán Rosales,</p>
        <p class="description d-flex justify-content-center">Sinaloa. México.</p>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Email:</p>
          <p class="description">info@eco-arado.com</p>
        </div>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Teléfono:</p>
          <p class="description">+52 667 531 4339</p>
        </div>
        <div class="d-flex flex-row justify-content-center">
          <p class="header mr-2">Celular:</p>
          <p class="description">+52 311 262 3949</p>
        </div>
      </div>
    </div>
  </div>

  <div class="d-none d-md-flex contact-image">
    <img class="w-100 h-100" src="/img/7.jpg" alt="Imagen de campo al fondo de la
                                                   caja de contacto de Ecoarado">
  </div>
</div>

app/views/main/_promotions.erb
<div id="promotions-container" class="d-flex flex-column flex-md-row promotions-container justify-content-between
                                      pt-0 pt-md-5 mt-4 mt-md-5 mx-3 mx-md-5">
  <div class="w-md-32 mb-3 mb-md-0">
    <div class="square-div">
      <div class="square-container">
        <img class="w-100 h-100 promotion-img" src="/img/6.jpg"
             alt="Promoción-Oferta">
      </div>
    </div>
  </div>

  <div class="w-md-32 mb-3 mb-md-0">
    <div class="square-div">
      <div class="square-container">
        <img class="w-100 h-100 promotion-img" src="/img/4.jpg"
             alt="Promoción-Oferta">
      </div>
    </div>
  </div>

  <div class="w-md-32">
    <div class="square-div">
      <div class="square-container">
        <img class="w-100 h-100 promotion-img" src="/img/5.jpg"
             alt="Promoción-Oferta">
      </div>
    </div>
  </div>
</div>

app/views/main/contact_us.erb
<div id="banners-container-mobile-contact-us" class="d-block d-md-none mt-3 w-75 mx-auto">
  <div class="banners-div-mobile-contact-us">
  </div>
</div>

<div id="banners-container-contact-us" class="d-none d-md-block w-75 mx-auto">
  <div class="banners-div-contact-us">
  </div>
</div>

<div class="d-flex flex-column w-75 mt-5 mt-md-5 mx-auto">
  <form id="form_contact_us">
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="inputFullName">*Nombre y Apellidos</label>
        <input type="text" class="form-control" id="inputFullName" required>
      </div>
      <div class="form-group col-md-12">
        <label for="inputEmail">*Correo Electrónico</label>
        <input type="email" class="form-control" id="inputEmail" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputPhone">*Celular</label>
        <input type="tel" class="form-control" id="inputPhone" maxlength="10" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputRegion">*Región</label>
        <input type="text" class="form-control" id="inputRegion" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCountry">*País</label>
        <input type="text" class="form-control" id="inputCountry" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputCrop">*Tipo de Cultivo</label>
        <input type="text" class="form-control" id="inputCrop" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputIrrigation">*Tipo de Riego</label>
        <input type="text" class="form-control" id="inputIrrigation" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputTractor">*Tipo de Tractor</label>
        <input type="text" class="form-control" id="inputTractor" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputTractorPower">*Potencia de su Tractor</label>
        <input type="text" class="form-control" id="inputTractorPower" required>
      </div>
      <div class="d-flex flex-column form-row col-md-6 mr-0 pr-0">
        <label for="inputDate">*Fecha y Hora para contactarlo</label>
        <div class="form-row ml-0">
          <div class="form-group col-md-6 mb-0">
            <input type="date" class="form-control" id="inputDate" required>
          </div>
          <div class="form-group col-md-6 mt-3 mb-3 mt-md-0 mb-md-0">
            <input type="time" class="form-control" id="inputTime" required>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group col-md-12 p-0">
      <label for="textareaMessage">*Mensaje</label>
      <textarea type="text" class="form-control" rows="3" id="textareaMessage" required></textarea>
    </div>

    <div class="d-flex justify-content-center">
      <button type="submit" class="btn btn-green">Enviar</button>
    </div>
  </form>
</div>

app/views/main/frequent_questions.html.erb
<h1>Main#frequent_questions</h1>
<p>Find me in app/views/main/frequent_questions.html.erb</p>

app/views/main/home.html.erb
<%= render 'banners' %>

<%= render 'promotions' %>

<%= render 'contact' %>

app/views/main/model_ea2.html.erb
<div class="d-flex flex-column mx-5">
  <div class="w-50">
    <div id="banners-container" class="d-none d-md-block">
      <div id="carouselBannerDesktop" class="banners-div carousel" data-interval="false" data-ride="carousel">
        <div class="carousel-indicators d-flex flex-column justify-content-center left-images-container
                    align-items-center col-md-1 m-0 mb-5 pr-0">
          <div data-target="#carouselBannerDesktop" data-slide-to="0" class="justify-content-center active mb-2 cursor-hand">
            <img src="/img/model_ea2/test.jpg"/>
          </div>
          <div data-target="#carouselBannerDesktop" data-slide-to="1" class="mb-2 cursor-hand">
            <img src="/img/model_ea2/test.jpg"/>
          </div>
          <div data-target="#carouselBannerDesktop" data-slide-to="2" class="cursor-hand">
            <img src="/img/model_ea2/test.jpg"/>
          </div>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="/img/model_ea2/modeloEA2.jpg" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="/img/banner-2.jpg" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="/img/banner-3.jpg" alt="Third slide">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex flex-column justify-content-center mx-auto w-md-50 mb-5 mb-md-0 mt-3 mt-md-3
              white-square">
    <h1 class="d-flex contact_us_title justify-content-center">Cotiza aquí</h1>
    <form id="form_model_ea2">
      <div class="form-row">
        <div class="form-group col-md-12">
          <label for="inputFullName">*Nombre y Apellidos</label>
          <input type="text" class="form-control" id="inputFullName" required>
        </div>
        <div class="form-group col-md-12">
          <label for="inputEmail">*Correo Electrónico</label>
          <input type="email" class="form-control" id="inputEmail" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputPhone">*Celular</label>
          <input type="tel" class="form-control" id="inputPhone" maxlength="10" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputRegion">*Región</label>
          <input type="text" class="form-control" id="inputRegion" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCountry">*País</label>
          <input type="text" class="form-control" id="inputCountry" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputCrop">*Tipo de Cultivo</label>
          <input type="text" class="form-control" id="inputCrop" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputIrrigation">*Tipo de Riego</label>
          <input type="text" class="form-control" id="inputIrrigation" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputTractor">*Tipo de Tractor</label>
          <input type="text" class="form-control" id="inputTractor" required>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputTractorPower">*Potencia de su Tractor</label>
          <input type="text" class="form-control" id="inputTractorPower" required>
        </div>
        <div class="form-row col-md-6 mr-0 pr-0">
          <label for="inputDate">*Fecha y Hora para contactarlo</label>
          <div class="form-group col-md-6 mr-0 pr-0">
            <input type="date" class="form-control" id="inputDate" required>
          </div>
          <div class="form-group col-md-6 mr-0 pr-0">
            <input type="time" class="form-control" id="inputTime" required>
          </div>
        </div>
      </div>
      <div class="form-group col-md-12 p-0">
        <label for="textareaMessage">*Mensaje</label>
        <textarea type="text" class="form-control" rows="3" id="textareaMessage" required></textarea>
      </div>

      <div class="d-flex justify-content-center">
        <button type="submit" class="btn btn-green">Enviar</button>
      </div>
    </form>
  </div>
</div>

app/views/main/who_we_are.html.erb
<h1>Main#who_we_are</h1>
<p>Find me in app/views/main/who_we_are.html.erb</p>

app/views/main_banners/_form.html.erb
<%= form_with(model: main_banner, local: true) do |form| %>
  <% if main_banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main_banner.errors.count, "error") %> prohibited this main_banner from being saved:</h2>

      <ul>
        <% main_banner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/main_banners/edit.html.erb
<h1>Editing Main Banner</h1>

<%= render 'form', main_banner: @main_banner %>

<%= link_to 'Show', @main_banner %> |
<%= link_to 'Back', main_banners_path %>

app/views/main_banners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Main Banners</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @main_banners.each do |main_banner| %>
      <tr>
        <td><%= main_banner.title %></td>
        <td><%= main_banner.order %></td>
        <td><%= link_to 'Show', main_banner %></td>
        <td><%= link_to 'Edit', edit_main_banner_path(main_banner) %></td>
        <td><%= link_to 'Destroy', main_banner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main Banner', new_main_banner_path %>

app/views/main_banners/new.html.erb
<h1>New Main Banner</h1>

<%= render 'form', main_banner: @main_banner %>

<%= link_to 'Back', main_banners_path %>

app/views/main_banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @main_banner.title %>
</p>

<%= image_tag(@main_banner.photo, width: 200) if @main_banner.photo.attached? %>

<p>
  <strong>Order:</strong>
  <%= @main_banner.order %>
</p>

<%= link_to 'Edit', edit_main_banner_path(@main_banner) %> |
<%= link_to 'Back', main_banners_path %>

app/views/shared/_admin_footer.erb
<h3>
  THIS THE ADMIN FOOTER
</h3>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>